modLoader="javafml"
loaderVersion="[36,)"
issueTrackerURL = "https://github.com/dragon-forge/HammerLib/issues"
license="All rights reserved"
[[mods]]
modId="hammerlib"
version="${file.jarVersion}"
displayName="HammerLib"
updateJSONURL = "https://api.modrinth.com/updates/PlkSuVtM/forge_updates.json"
displayURL = "https://modrinth.com/mod/PlkSuVtM"
logoFile="logo.png" #optional
authors="Zeitheron" #optional
description='''
HammerLib is an essential tool for developing mods easily.
Packed with a lot of utilities, this library provides nearly anything a modder would need, in one handy mod!
'''
[[dependencies.hammerlib]]
    modId="forge"
    mandatory=true
    versionRange="[36,)"
    ordering="NONE" # NONE/BEFORE/AFTER
    side="BOTH"
[[dependencies.hammerlib]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16.5]"
    ordering="NONE"
    side="BOTH"
