modLoader = "javafml"
loaderVersion = "[44,)"
issueTrackerURL = "https://github.com/dragon-forge/HammerLib/issues"
license = "All rights reserved"
[[mods]]
modId = "hammerlib"
version = "${file.jarVersion}"
displayName = "HammerLib"
updateJSONURL="https://api.modrinth.com/updates/PlkSuVtM/forge_updates.json"
displayURL = "http://h.zeith.org/api/fmlhp/247401"
logoFile = "logo.png"
authors = "Zeitheron"

description = '''
HammerLib is an essential tool for developing mods easily.
Packed with a lot of utilities, this library provides nearly anything a modder would need, in one handy package!
'''

[[dependencies.hammerlib]]
modId = "forge"
mandatory = true
versionRange = "[44.1,)"
ordering = "NONE" # NONE/BEFORE/AFTER
side = "BOTH"

[[dependencies.hammerlib]]
modId = "minecraft"
mandatory = true
versionRange = "[1.19.3,1.20)"
ordering = "NONE"
side = "BOTH"
