package org.zeith.hammerlib.api.crafting.building;

import com.google.gson.*;
import net.minecraft.resources.ResourceLocation;
import net.minecraft.util.GsonHelper;
import org.zeith.hammerlib.HammerLib;
import org.zeith.hammerlib.api.crafting.itf.IFileDecoder;

import java.io.*;
import java.util.Locale;
import java.util.Optional;

public class GsonFileDecoder
		implements IFileDecoder<JsonElement>
{
	public static final Gson GSON = (new GsonBuilder()).setPrettyPrinting().disableHtmlEscaping().create();
	
	private static final String PATH_SUFFIX = ".json";
	private static final int PATH_SUFFIX_LENGTH = PATH_SUFFIX.length();
	
	final String directory, directoryLower;
	private final Gson gson;
	
	public GsonFileDecoder(String directory)
	{
		this(directory, GSON);
	}
	
	public GsonFileDecoder(String directory, Gson gson)
	{
		this.directory = directory;
		this.directoryLower = directory.toLowerCase(Locale.ROOT);
		this.gson = gson;
	}
	
	@Override
	public boolean doesPathMatch(ResourceLocation location)
	{
		var s = location.getPath().toLowerCase(Locale.ROOT);
		return s.endsWith(PATH_SUFFIX) && s.startsWith(this.directoryLower);
	}
	
	@Override
	public ResourceLocation transformPathToId(ResourceLocation location)
	{
		int i = this.directory.length() + 1;
		var s = location.getPath();
		int endIndex = s.length() - PATH_SUFFIX_LENGTH;
		
		// Generated by ChatGPT :D
		if (i < 0 || i > endIndex || endIndex > s.length()) return null;
		
		return new ResourceLocation(location.getNamespace(), s.substring(i, endIndex));
	}
	
	@Override
	public Optional<JsonElement> tryDecode(ResourceLocation path, BufferedReader reader) throws IOException
	{
		try
		{
			return Optional.ofNullable(GsonHelper.fromJson(this.gson, reader, JsonElement.class));
		} catch(IllegalArgumentException | JsonParseException err)
		{
			HammerLib.LOG.error("Couldn't parse data file {} from {}", transformPathToId(path), path, err);
		}
		
		return Optional.empty();
	}
	
	@Override
	public void write(JsonElement data, BufferedWriter writer) throws IOException
	{
		writer.write(GSON.toJson(data));
	}
}